### ISSUE TITLE
Yan-C-Bin duplicate

### ISSUE THREAD

**Issue by BrianWendt** [theoperatore/dnd-monster-api#2]
729 and 761 are almost identical. However, it appears that 729 is more complete.

**Comment by theoperatore** [comment]
@BrianWendt hey! sorry for the late reply!

Thanks for flagging. I'll check to see what's going on. Maybe just an artifact of duplicate runs or changing data. If 729 is more complete then maybe removing 761 makes the most sense.

**Comment by theoperatore** [comment]
Hmm so it seems the original source has changed their format for their monster descriptions (it actually makes it easier to parse). 

However, there are some duplicates in the original data too that will definitely transfer to this project. 

Until a new parser can be built to handle the new format, unfortunately we're going to have to live with the duplicates in this dataset. :(

**Comment by BrianWendt** [comment]
How often are you re-parsing?
I've not looked at the parser code itself, just the results, but maybe there could be a post process that detects duplicates and flags them for review.
I'll try taking a look later.

**Comment by theoperatore** [comment]
I haven't parsed in a while. It's a very manual process. you have to literally checkout the code, run `yarn build-db` and the git commit/push back to master.

The parser isn't built very well, it's very fast and completely coupled to the structure of the repository that it get's content from. That structure _just_ changed. We're going to have stale data until a new parser can be built.

A post process for detecting duplicates sounds pretty nice! would be pretty cool to have.

**Comment by theoperatore** [comment]
gonna close this issue for now because the parser has been rewritten to be able to pull latest from the source. 

We can revisit this if it's a problem in the future.
